### ISSUE TITLE
Swap API

### ISSUE THREAD

**Issue by tomt1664** [commerceblock/mercury#27]
Develop protocol and implementation to enable atomic swaps. 

The server will receive a request to update a collection of states simultaneously, signed by all owners.

**Comment by tomossomot** [comment]
Currenlty there the transfer protocol is implemented as two functions. The sender calls `transfer_sender()` to performs their half of the protocol and the receiver calls `transger_receiver()` to perform their half and thus complete the transfer.

For the StateChain Entity side of swaps we require a `transfer_sender_batch()` function which takes a list of:

- Shared key ID
- StateChain signatures of transfer

for each participant in the Swap Pool. The server then waits for each of the corresponding `transfer_receiver()` calls to complete before marking all transfers as complete. If one or more transfers are not complete after some amount of time the batch transfer is cancelled.   

As for DoS protections there needs to be a way for the State entity to identify which participant to punish in the event of a failed protocol run. For 2-party swaps this is straight forward. For multi-party swaps perhaps each participant commit to their input UTXO when carrying out `transfer_receiver()`, which can later be requested for reveal by the StateChain Entity if some particiaptns do not complete their transfers in time. SCE can then link the completed transfers with their original owners and punish those whose commitments are not present. The swap pool can then restart with a new owner-to-UTXO swap mapping.

**Comment by tomossomot** [comment]
The following failure circumstances can occur for an individual transfer:

1) Sender fails to complete `transfer_sender`
2) Sender fails to send the transfer informtion to Receiver
3) Receiver fails to complete `transfer_receiver`

It is obvious to the server who to punish if 1) occurs. They can request all commitments to be revealed and punish any state chains which are not present.

However in the cases of 2) and 3) the server does not know whether Sender failed to send the transfer message to Receiver or whether Receiver failed to complete their end of the protocol. Therefore both parties must be punished here which is a bit clumsy IMO.

Another option is to have transfer messages passed via the swap pool coordinator and have punishments carried out by the coordinator since they would be able to tell the difference between a 2) and a 3) failure. However this adds quite a bit of complexity:

A failed batch transfer still costs the SCE so a fidelity bond would have to be provided by the coordinator for each run. Now the coordinator must fund the fidelity bond somehow and so would have to have their own fidelity bond system for each participant in the batch-transfer (A coordinator would not be willing to lose a fidelity bond of their own coins if it is a participant's fault that the batch-transfer failed). 

To verify that a valid message has been sent from Sender to Receiver some kind of `transfer_receiver` failure proof could be generated by the SCE after attempting to perform the function with the message passed from Sender could be imlemented.

**Comment by tomossomot** [comment]
# Coordinator

A swap is an atomic batch-transfer of UTXOs between `n` participants.  A swap is initiated by a coordinator providing a `batch_id` and `n` signatures - one from each participant. The signatures sign for their UTXO to be involved in a swap with a particular `batch_id` and to occur within some time frame. Once the desired number of participants is reached the coordinator matches senders and receivers together for each individual transfer. The swap can then commence. 

Details of matching and communication are omitted, this post is specifically about models for where the coordination should be run and by whom.


## Dedicated Coordinator daemon

In this model a seperate coordination daemon advertises swap rounds for other participants to join. When enough participants have signalled interest in a swap the coordinator can gather all signatures and begin the protocol. It can be run by anybody and the coordinator does not have to take part themselves.

Coordinators can build reputation and advertise regular swap patterns. This may allow for swaps with larger anonymity sets since wallets can know when best to swap for their utxo amount. Swap amounts are chosen by the coordinator so a standard of swapable UTXO amounts will emerge. (EG: Coordinator A runs swaps of 1,2 and 3 BTC every evening).

Protecting from spam may be difficult since communication should all be over Tor. A coordinator can refuse to serve a particular UTXO if it is found misbehaving but then risk banning an honest user who happens to be transferred that UTXO in the future.


## Wallets act as Coordinator

A bulletin board of all online participants wishing to swap is accessible through the wallet. A user can query for all particiapnts with the same UTXO amount as them and propose a swap. This can be done automatically in the background and without user interaction. Wallets should prioritise accepting swaps rather than proposing them. 

No extra software or specialised roles are required for this method - each wallet should have the capability to propose a swap. This makes small and fast swapping extremely simple but may make it harder to come across larger anonymity set swaps because wallets may accept a swap as soon as it arrives instead of waiting for more participants to join.

Preventing spam in this model is tricky.
 

## StateChain Entity is Coordinator

Works similar to dedicated Coordinator daemon but StateChain Entity is the only server. Several swap pools are advertised for different amounts and anonymity set sizes. Wallets alert SCE of their desire to swap and wait for a round to start. 

Liveness of the entire State Chain system is dependent on the SCE already so there is no added liveness risk. 

The problem of DoS protection found in both other models can be handled here as the SCE can block a UTXO from transferring for some period of time.
